In [7]:
import sys
import os
import pandas as pd

sys.path.append(os.path.abspath("../../../"))
PROJECT_ROOT = "../../../"

import lib.experimentation.experiments as exp
import lib.visualization.result_processing as processing
import lib.feature_selection.statistical_methods as stats_fs
import lib.learning_algorithms.classical as classical
import lib.learning_algorithms.domain_aware as domain_aware
import lib.learning_algorithms.ensemble as ensemble

# Load

In [8]:
intra_result_df, _ = exp.load_results("results_fs/", "intra")
inter_session_result_df, _ = exp.load_results("results_fs/", "inter_session")
inter_subject_result_df, _ = exp.load_results("results_fs/", "inter_subject")

In [9]:
intra_metrics_df, intra_summary_df = processing.compute_metrics_table(intra_result_df)
inter_session_metrics_df, inter_session_summary_df = processing.compute_metrics_table(inter_session_result_df)
inter_subject_metrics_df, inter_subject_summary_df = processing.compute_metrics_table(inter_subject_result_df)

# Evaluating

In [10]:
intra_summary_df

,model,fs_method,split,accuracy_mean,accuracy_std,f1_macro_mean,f1_macro_std,n_samples_total
0,nn_erm,pca_32,test,0.399745,0.11619,0.394218,0.11685,1566
1,nn_erm,pca_32,train,1.000000,0.00000,1.000000,0.00000,3618

In [11]:
inter_session_summary_df

,model,fs_method,split,accuracy_mean,accuracy_std,f1_macro_mean,f1_macro_std,n_samples_total
0,nn_erm,pca_32,test,0.397377,0.106677,0.387262,0.104732,5184
1,nn_erm,pca_32,train,0.999807,0.000818,0.999807,0.000818,5184

In [12]:
inter_subject_summary_df

,model,fs_method,split,accuracy_mean,accuracy_std,f1_macro_mean,f1_macro_std,n_samples_total
0,nn_erm,pca_32,test,0.281057,0.029327,0.247025,0.042417,5184
1,nn_erm,pca_32,train,0.965302,0.015953,0.965318,0.015919,41472

# Plots Latter