In [309]:
import sys
import os
import pandas as pd

sys.path.append(os.path.abspath("../../../"))
PROJECT_ROOT = "../../../"

import lib.experimentation.experiments as exp
import lib.visualization.result_processing as processing
import lib.feature_selection.statistical_methods as stats_fs
import lib.learning_algorithms.classical as classical
import lib.learning_algorithms.domain_aware as domain_aware
import lib.learning_algorithms.ensemble as ensemble

# Load

In [310]:
intra_result_df, _ = exp.load_results("results_model/", "intra")
inter_session_result_df, _ = exp.load_results("results_model/", "inter_session")
inter_subject_result_df, _ = exp.load_results("results_model/", "inter_subject")
global_result_df, _ = exp.load_results("results_model/", "global")

In [311]:
intra_metrics_df, intra_summary_df = processing.compute_metrics_table(intra_result_df)
inter_session_metrics_df, inter_session_summary_df = processing.compute_metrics_table(inter_session_result_df)
inter_subject_metrics_df, inter_subject_summary_df = processing.compute_metrics_table(inter_subject_result_df)
global_metrics_df, global_summary_df = processing.compute_metrics_table(global_result_df)

# Evaluating

In [312]:
intra_metrics_df[intra_metrics_df["split"] == "test"]

,subject,session,model,fs_method,split,accuracy,f1_macro,n_samples
0,A01,session1,nn_domain_agreement,mi,test,0.724138,0.723319,58
2,A01,session1,nn_erm,mi,test,0.741379,0.744864,58
4,A01,session2,nn_domain_agreement,mi,test,0.706897,0.706691,58
6,A01,session2,nn_erm,mi,test,0.741379,0.739887,58
8,A02,session1,nn_domain_agreement,mi,test,0.586207,0.579762,58
10,A02,session1,nn_erm,mi,test,0.637931,0.638218,58
12,A02,session2,nn_domain_agreement,mi,test,0.413793,0.414815,58
14,A02,session2,nn_erm,mi,test,0.431034,0.432214,58
16,A03,session1,nn_domain_agreement,mi,test,0.758621,0.760189,58
18,A03,session1,nn_erm,mi,test,0.775862,0.775651,58
20,A03,session2,nn_domain_agreement,mi,test,0.637931,0.634650,58
22,A03,session2,nn_erm,mi,test,0.672414,0.666838,58
24,A04,session1,nn_domain_agreement,mi,test,0.310345,0.308333,58
26,A04,session1,nn_erm,mi,test,0.327586,0.323335,58
28,A04,session2,nn_domain_agreement,mi,test,0.603448,0.591639,58
30,A04,session2,nn_erm,mi,test,0.568966,0.556110,58
32,A05,session1,nn_domain_agreement,mi,test,0.275862,0.270191,58
34,A05,session1,nn_erm,mi,test,0.310345,0.316121,58
36,A05,session2,nn_domain_agreement,mi,test,0.362069,0.361458,58
38,A05,session2,nn_erm,mi,test,0.344828,0.341183,58
40,A06,session1,nn_domain_agreement,mi,test,0.327586,0.314277,58
42,A06,session1,nn_erm,mi,test,0.310345,0.311889,58
44,A06,session2,nn_domain_agreement,mi,test,0.413793,0.408189,58
46,A06,session2,nn_erm,mi,test,0.327586,0.320285,58
48,A07,session1,nn_domain_agreement,mi,test,0.758621,0.755875,58
50,A07,session1,nn_erm,mi,test,0.741379,0.740638,58
52,A07,session2,nn_domain_agreement,mi,test,0.620690,0.609924,58
54,A07,session2,nn_erm,mi,test,0.586207,0.568609,58
56,A08,session1,nn_domain_agreement,mi,test,0.568966,0.561946,58
58,A08,session1,nn_erm,mi,test,0.586207,0.575607,58
60,A08,session2,nn_domain_agreement,mi,test,0.672414,0.661686,58
62,A08,session2,nn_erm,mi,test,0.741379,0.739070,58
64,A09,session1,nn_domain_agreement,mi,test,0.500000,0.499032,58
66,A09,session1,nn_erm,mi,test,0.568966,0.555023,58
68,A09,session2,nn_domain_agreement,mi,test,0.620690,0.628260,58
70,A09,session2,nn_erm,mi,test,0.706897,0.713571,58

In [313]:
intra_summary_df[intra_summary_df["split"] == "test"]

,model,fs_method,split,accuracy_mean,accuracy_std,f1_macro_mean,f1_macro_std,n_samples_total
0,nn_domain_agreement,mi,test,0.547893,0.160169,0.543902,0.161135,1044
2,nn_erm,mi,test,0.562261,0.174143,0.558840,0.174542,1044

In [314]:
inter_session_summary_df[inter_session_summary_df["split"] == "test"]

,model,fs_method,split,accuracy_mean,accuracy_std,f1_macro_mean,f1_macro_std,n_samples_total
0,nn_domain_agreement,mi,test,0.506366,0.136022,0.495228,0.139444,5184
2,nn_erm,mi,test,0.501543,0.143743,0.489102,0.147548,5184

In [315]:
inter_subject_summary_df[inter_subject_summary_df["split"] == "test"]

,model,fs_method,split,accuracy_mean,accuracy_std,f1_macro_mean,f1_macro_std,n_samples_total
0,nn_erm,mi,test,0.312114,0.064159,0.271291,0.070734,5184
2,nn_pred_vapnik,mi,test,0.308449,0.052213,0.261448,0.078149,5184

In [316]:
global_summary_df

,model,fs_method,split,accuracy_mean,accuracy_std,f1_macro_mean,f1_macro_std,n_samples_total
0,nn_domain_agreement,mi,test,0.373563,NaN,0.360669,NaN,1044
1,nn_domain_agreement,mi,train,0.418116,NaN,0.406353,NaN,4140
2,nn_erm,mi,test,0.505747,NaN,0.503961,NaN,1044
3,nn_erm,mi,train,0.932367,NaN,0.932164,NaN,4140

# Plots Latter